spring:
  application:
    name: reservation-event-processor
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

server:
  port: ${SERVER_PORT}

# Keycloak Configuration
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT_ID}
  credentials: 
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true

logging:
  level:
    it.polito.cloudresources.eventprocessor: INFO

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info # Expose health and info endpoints
  endpoint:
    health:
      probes:
        enabled: true # Enable Kubernetes probes
