apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-event-processor-config
  namespace: resource-reservation # Assuming the same namespace as other components
data:
  SPRING_PROFILES_ACTIVE: "pro" # Or "test", "dev" depending on the environment
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/resourcemgmt" # Example, adjust as needed
  # Add other non-sensitive configurations here
  LOGGING_LEVEL_ROOT: "INFO"
  # Assuming DateTimeUtils needs a default zone ID
  APP_DEFAULT_ZONE_ID: "Europe/Rome"
