apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-event-processor-deployment
  namespace: resource-reservation # Assuming the same namespace
  labels:
    app: reservation-event-processor
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: reservation-event-processor
  template:
    metadata:
      labels:
        app: reservation-event-processor
    spec:
      containers:
      - name: reservation-event-processor
        image: your-docker-registry/reservation-event-processor:latest # Replace with your actual image path
        ports:
        - containerPort: 8080 # Default Spring Boot port, expose if health checks are needed
        envFrom:
        - configMapRef:
            name: reservation-event-processor-config
        - secretRef:
            name: reservation-event-processor-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
      imagePullSecrets:
      - name: your-registry-secret # Add if using a private registry
