apiVersion: v1
kind: Secret
metadata:
  name: reservation-event-processor-secret
  namespace: resource-reservation # Assuming the same namespace
type: Opaque
data:
  # Passwords should be base64 encoded
  # Example: echo -n 'your_password' | base64
  SPRING_DATASOURCE_USERNAME: "dXNlcg==" # Placeholder for base64 encoded username
  SPRING_DATASOURCE_PASSWORD: "cGFzc3dvcmQ=" # Placeholder for base64 encoded password
  # Add other secrets if needed
